spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/simple_login_db
        username: admin
        password: admin
        driver-class-name: org.postgresql.Driver
    
    flyway:
        enabled: true
        locations: 
            - classpath:db/migration/auth
        schemas: auth
        create-schemas: true
        baseline-on-migrate: false

    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                